RealState/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
from django.urls import include, path

urlpatterns = [
    path('RealStateJA/', include('RealStateJA.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # other URL patterns go here
]

RealStateJA/urls.py
from django.urls import path
from . import views
from .views import custom_user_creation_view


urlpatterns = [
    path('signup/', views.custom_user_creation_view, name='signup'),
    path('success/', views.success_view, name='success'),
    path('home/', views.home, name='home'),
    path('renter/', views.renter, name='renter'),
    path('agentview/', views.agentview, name='agentview'),
    path('payinfomod/', views.payinfomod, name='payinfomod'),
    path('billingsuccess/', views.billingsuccess, name='billingsuccess'),
    path('addinfomod/', views.addinfomod, name='addinfomod'),
    path('addsuccess/', views.addsuccess, name='addsuccess'),
    path('propertyview/', views.add_property, name='propertyview'),
    path('propertysuccess/', views.propertysuccess, name='propertysuccess'),
    path('propertyselection/', views.propertyselection, name='propertyselection'),
    path('housesearch/', views.housesearch, name='housesearch'),
    path('apartmentsearch/', views.apartmentsearch, name='apartmentsearch'),
    path('commercialsearch/', views.commercialsearch, name='commercialsearch'),
    path('book/', views.book, name='book'),
    path('successfulbooking/', views.successfulbooking, name='successfulbooking'),
    path('managebookinga/', views.managebookinga, name='managebookinga'),
    path('managebookingsr/', views.managebookingsr, name='managebookingsr'),
    path('bookrent/', views.bookrent, name='bookrent'),
    path('bookdeleter/', views.bookdeleter, name='bookdeleter'),
    path('bookview/', views.bookview, name='bookview'),
    path('bookagent/', views.bookagent, name='bookagent'),
    path('agentcancel/', views.agentcancel, name='agentcancel'),




    # other URL patterns go here
]

RealStateJA/models.py
from django.db import models


class person_user(models.Model):
    email_address = models.CharField(max_length=25, primary_key=True)
    name = models.CharField(max_length=20)

    class Meta:
        db_table = 'person_user'

class agent(models.Model):
    email_address = models.CharField('person_user', primary_key=True)
    agency = models.CharField(max_length=25)
    license_number = models.CharField(max_length=5)
    commission_rate = models.CharField(max_length=4)


    class Meta:
        db_table = 'agent'

class perspective_renter(models.Model):
    email_address = models.CharField('person_user', primary_key=True)
    desired_move_in_date = models.DateField()
    preferred_location_city = models.CharField(max_length=20)
    preferred_location_state = models.CharField(max_length=15)
    budget = models.IntegerField()

    class Meta:
        db_table = 'perspective_renter'


class property(models.Model):
    property_id = models.AutoField(primary_key=True)
    agency = models.CharField(max_length=15)
    location_address = models.CharField(max_length=20)
    location_city = models.CharField(max_length=20)
    location_state = models.CharField(max_length=15)
    availability = models.DateField()
    listing_type=models.CharField(max_length=10)
    building_type=models.CharField(max_length=15)
    class Meta:
        db_table = 'property'


class house(models.Model):
    property_id = models.IntegerField('property', primary_key=True)
    number_of_rooms = models.IntegerField()
    square_footage = models.IntegerField()
    description = models.CharField(max_length=200)
    price = models.IntegerField()

    class Meta:
        db_table = 'house'


class apartment(models.Model):
    property_id = models.IntegerField('property', primary_key=True)
    number_of_rooms = models.IntegerField()
    square_footage = models.IntegerField()
    description = models.CharField(max_length=200)
    price = models.IntegerField()

    class Meta:
        db_table = 'apartment'


class commercial_building(models.Model):
    property_id = models.IntegerField('property', primary_key=True)
    square_footage = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.CharField(max_length=200)
    type_of_business = models.CharField(max_length=20)
    price = models.IntegerField()

    class Meta:
        db_table = 'commercial_building'


class credit_card(models.Model):
    email_address = models.CharField('person_user')
    card_number = models.CharField(primary_key=True,  max_length=19)
    billing_address = models.CharField(max_length=35)
    cardholder_name = models.CharField(max_length=25)

    class Meta:
        db_table = 'credit_card'


class booking(models.Model):
    property_id = models.IntegerField('property', primary_key=True)
    start_booking_date = models.DateField()
    end_booking_date = models.DateField()
    card_number = models.CharField('credit_card', max_length=19)
    email_address = models.CharField('person_user')
    class Meta:
        db_table = 'booking'


class email_address_telephone(models.Model):
    email_address = models.CharField('person_user', primary_key=True)
    telephone = models.CharField(max_length=16)

    class Meta:
        db_table = 'email_address_telephone'


class user_address(models.Model):
    email_address = models.CharField('person_user', primary_key=True, default=None)
    street_street_number = models.CharField(max_length=5)
    street_street_name = models.CharField(max_length=20)
    street_apt_number = models.CharField(max_length=10, null=True)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=15)
    zip = models.CharField(max_length=5)

    class Meta:
        db_table = 'user_address'

class house_location(models.Model):
    house_location_id = models.IntegerField(primary_key=True)
    street_street_number = models.CharField(max_length=5)
    street_street_name = models.CharField(max_length=20)
    zip = models.CharField(max_length=5)

    class Meta:
        db_table = 'house_location'


class apartment_location(models.Model):
    apartment_location_id = models.IntegerField(primary_key=True)
    street_street_number = models.CharField(max_length=5)
    street_street_name = models.CharField(max_length=20)
    street_apt_number = models.CharField(max_length=5)
    zip = models.CharField(max_length=5)

    class Meta:
        db_table = 'apartment_location'



class commercial_building_location(models.Model):
    commercial_building_location_id = models.IntegerField(primary_key=True)
    street_street_number = models.CharField(max_length=5)
    street_street_name = models.CharField(max_length=20)
    street_apt_number = models.CharField(max_length=5)
    zip = models.CharField(max_length=5)

    class Meta:
        db_table = 'commercial_building_location'

RealStateJA/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import person_user

class CustomUserCreationForm(forms.ModelForm):
    name = forms.CharField(max_length=20)
    email = forms.EmailField()
    

    class Meta:
        model = person_user
        fields = ('email', 'name')

RealStateJA/views.py
from django.shortcuts import render, redirect
from .models import person_user, user_address, agent, perspective_renter, email_address_telephone, credit_card, property, apartment, house, commercial_building, booking
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.db import connection
from django.contrib import messages


def home(request):
    return render(request, 'RealStateJA/home.html')

def renter(request):
    return render(request, 'RealStateJA/renter.html')

def agentview(request):
    return render(request, 'RealStateJA/agentview.html')

def success_view(request):
    return render(request, 'RealStateJA/success.html')

def billingsuccess(request):
    return render(request, 'RealStateJA/billingsuccess.html')

def addsuccess(request):
    return render(request, 'RealStateJA/addsuccess.html')

def propertysuccess(request):
    return render(request, 'RealStateJA/propertysuccess.html')

def propertyselection(request):
    return render(request, 'RealStateJA/propertyselection.html')

def housesearch(request):
    return render(request, 'RealStateJA/housesearch.html')

def apartmentsearch(request):
    return render(request, 'RealStateJA/apartmentsearch.html') 

def commercialsearch(request):
    return render(request, 'RealStateJA/commercialsearch.html')

def bookagent(request):
    return render(request, 'RealStateJA/bookagent.html')       



def custom_user_creation_view(request):
    if request.method == 'POST':
        # Get the form data
        name = request.POST.get('name')
        email_address = request.POST.get('email_address')
        telephone = request.POST.get('telephone')
        street_street_number = request.POST.get('street_street_number')
        street_street_name = request.POST.get('street_street_name')
        street_apt_number = request.POST.get('street_apt_number')
        city = request.POST.get('city')
        state = request.POST.get('state')
        zip = request.POST.get('zip')
        user_type = request.POST.get('user_type')

        # Check if the user already exists
        existing_user = person_user.objects.filter(email_address=email_address).first()
        if existing_user:
            # Handle existing user error
            error_message = 'User already exists.'
            return render(request, 'RealStateJA/signup.html', {'error_message': error_message})


        new_user = person_user.objects.create(
            email_address=email_address,
            name=name
        )

        new_user_address = user_address.objects.create(
            street_street_number=street_street_number,
            street_street_name=street_street_name,
            street_apt_number=street_apt_number,
            city=city,
            state=state,
            zip=zip,
            email_address=new_user.email_address
        )

        new_user_telephone = email_address_telephone.objects.create(
            email_address=new_user.email_address,
            telephone=telephone,)


        # Create a new Agent or Renter object, depending on user_type
        if user_type == 'agent':
            new_agent = agent.objects.create(
                email_address=new_user.email_address,
                agency=request.POST.get('agency'),
                license_number=request.POST.get('license_number'),
                commission_rate=request.POST.get('commission_rate'),
            )
        elif user_type == 'renter':
            new_perspective_renter = perspective_renter.objects.create(
                email_address=new_user.email_address,
                desired_move_in_date=request.POST.get('desired_move_in_date'),
                preferred_location_city=request.POST.get('preferred_location_city'),
                preferred_location_state=request.POST.get('preferred_location_state'),
                budget=request.POST.get('budget'),
            )
            new_credit_card = credit_card.objects.create(
                email_address=new_user.email_address,
                card_number=request.POST.get('card_number'),
                billing_address=request.POST.get('billing_address'),
                cardholder_name=request.POST.get('cardholder_name'),
            )
        return redirect(reverse_lazy('success'))

    return render(request, 'RealStateJA/signup.html')


def payinfomod(request):
    if request.method == 'POST':
        email_address = request.POST['email_address']
        card_number = request.POST['card_number']
        billing_address = request.POST['billing_address']
        cardholder_name = request.POST['cardholder_name']

        # Check if the email exists in person_user table
        try:
            user = person_user.objects.get(email_address=email_address)
        except person_user.DoesNotExist:
            error_message = 'User does not exist'
            return render(request, 'RealStateJA/payinfomod.html', {'error_message': error_message})

        # Check if the credit card exists in the credit_card table
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM credit_card WHERE email_address=%s", [email_address])
            row = cursor.fetchone()
            if row:
                # Update the row with new information
                cursor.execute("UPDATE credit_card SET card_number=%s, billing_address=%s, cardholder_name=%s WHERE email_address=%s", [card_number, billing_address, cardholder_name, email_address])
                return redirect(reverse_lazy('billingsuccess'))
            else:
                # Insert new row
                cursor.execute("INSERT INTO credit_card (email_address, card_number, billing_address, cardholder_name) VALUES (%s, %s, %s, %s)", [email_address, card_number, billing_address, cardholder_name])
                return redirect(reverse_lazy('billingsuccess'))

        return redirect('payinfomod')

    return render(request, 'RealStateJA/payinfomod.html')


def addinfomod(request):
    if request.method == 'POST':
        email_address = request.POST['email_address']
        street_street_number = request.POST['street_street_number']
        street_street_name = request.POST['street_street_name']
        street_apt_number = request.POST['street_apt_number']
        city = request.POST['city']
        state = request.POST['state']
        zip = request.POST['zip']

        # Check if the email exists in person_user table
        try:
            user = person_user.objects.get(email_address=email_address)
        except person_user.DoesNotExist:
            error_message = 'User does not exist'
            return render(request, 'RealStateJA/addinfomod.html', {'error_message': error_message})

        # Check if the credit card exists in the credit_card table
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM user_address WHERE email_address=%s", [email_address])
            row = cursor.fetchone()
            if row:
                # Update the row with new information
                cursor.execute("UPDATE user_address SET street_street_number=%s, street_street_name=%s, street_apt_number=%s, city=%s, state=%s, zip=%s WHERE email_address=%s", [street_street_number, street_street_name, street_apt_number, city, state, zip, email_address])
                return redirect(reverse_lazy('addsuccess'))
            else:
                # Insert new row
                cursor.execute("INSERT INTO credit_card (email_address, street_street_number, street_street_name, street_apt_number, city, state, zip) VALUES (%s, %s, %s, %s, %s, %s, %s)", [email_address, street_street_number, street_street_name, street_apt_number, city, state, zip])
                return redirect(reverse_lazy('addsuccess'))

        return redirect('addinfomod')

    return render(request, 'RealStateJA/addinfomod.html')


def add_property(request):
    if request.method == 'POST':
        # Get the form data
        agency = request.POST.get('agency')
        location_address = request.POST.get('location_address')
        location_city = request.POST.get('location_city')
        location_state = request.POST.get('location_state')
        listing_type = request.POST.get('listing_type')
        availability = request.POST.get('availability')
        building_type = request.POST.get('building_type')
        square_footage = request.POST.get('square_footage')
        description = request.POST.get('description')
        price= request.POST.get('price')
        number_of_rooms = request.POST.get('number_of_rooms')


        new_property = property.objects.create(
            agency = agency,
            location_address = location_address,
            location_city = location_city,
            location_state = location_state,
            availability = availability,
            listing_type=listing_type,
            building_type=building_type,
        )

        # Create a new House, Apartment or Commercial object, depending on building_type
        if building_type == 'House':
            new_house = house.objects.create(
                property_id=new_property.property_id,
                number_of_rooms=number_of_rooms,
                square_footage=square_footage,
                description=description,
                price=price,
            )
        elif building_type == 'Apartment':
            new_apartment = apartment.objects.create(
                property_id=new_property.property_id,
                number_of_rooms=request.POST.get('number_of_rooms'),
                square_footage=square_footage,
                description=description,
                price=price
            )
        elif building_type == 'Commercial':
            new_commercial = commercial_building.objects.create(

RealStateJA/templates/RealStateJA/addinfomod.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Address Info Modification</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
    }
    h1 {
      text-align: center;
    }
    form {
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      border: 1px solid #ccc;
      border-radius: 10px;
    }
    fieldset {
      border: none;
      margin-bottom: 20px;
    }
    label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }
    input[type="text"], input[type="number"], input[type="date"] {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
      box-sizing: border-box;
      margin-bottom: 20px;
    }
    input[type="radio"] {
      margin-right: 5px;
    }
    button[type="submit"], button {
      background-color: #4CAF50;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }
    fieldset {
      border: 2px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin-bottom: 20px;
    }

    legend {
      font-size: 1.2em;
      font-weight: bold;
      margin-bottom: 10px;
    }
    button[type="submit"]:hover, button:hover {
      background-color: #3e8e41;
    }
  </style>
</head>
<body>
  <h1>Add/Modify Address Information</h1>
  <a href="{% url 'home' %}"><button>Go back to Home</button></a>
  <form method="POST">
    {% csrf_token %}
    <fieldset>
      <legend>Enter your new address information</legend>
      <label for="email_address">Email Address:</label><br>
      <input type="text" id="email_address" name="email_address"><br><br>
      {% if error_message %}
        <p class="error">{{ error_message }}</p>
      {% endif %}
      <label for="street_street_number">Street Number:</label><br>
      <input type="text" name="street_street_number" id="street_street_number"><br><br>
      <label for="street_street_name">Street Name:</label><br>
      <input type="text" name="street_street_name" id="street_street_name"><br><br>
      <label for="street_apt_number">Apartment Number:</label><br>
      <input type="text" name="street_apt_number" id="street_apt_number"><br><br>
      <label for="city">City</label><br>
      <input type="text" name="city" id="city"><br><br>
      <label for="state">State</label><br>
      <input type="text" name="state" id="state"><br><br>
      <label for="zip">Zip</label><br>
      <input type="text" name="zip" id="zip"><br><br>
    </fieldset>
    <button type="submit">Submit</button>
  </form

RealStateJA/templates/RealStateJA/agentview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Agent Actions</title>
    <style>
  		body {
  			font-family: Arial, sans-serif;
  			background-color: #f2f2f2;
  			margin: 0;
  			padding: 0;
  		}

  		h1 {
  			text-align: center;
  			margin-top: 50px;
  		}

  		button {
  			background-color: #4CAF50;
  			color: white;
  			padding: 12px 20px;
  			border: none;
  			border-radius: 4px;
  			cursor: pointer;
  			margin: 10px;
  			font-size: 16px;
  			font-weight: bold;
  		}

  		button:hover {
  			background-color: #3e8e41;
  		}

  		a {
  			text-decoration: none;
  		}

  		.container {
  			display: flex;
  			justify-content: center;
  			align-items: center;
  			height: 100vh;
  		}

  		.buttons {
  			display: flex;
  			flex-wrap: wrap;
  			justify-content: center;
  			align-items: center;
  		}
  	</style>
</head>
<body>
    <h1>Agent Actions</h1>
    <nav>
        <ul>
            <li><a href="{% url 'propertyview' %}"><button>Add/Delete/Modify properties</button></a></li>
            <li><a href="{% url 'propertyselection' %}"><button>Search for Properties</button></a></li>
			<li><a href="{% url 'bookagent' %}"><button>Manage Bookings</button></a></li>
            <li><a href="{% url 'home' %}"><button>Go back to Home</button></a></li>
        </ul>
    </nav>
</body>
</html>

RealStateJA/templates/RealStateJA/billingsuccess.html
<div class="success-message">
  <i class="fa fa-check-circle"></i>
  <p>Your billing information has been updated successfully!</p>
</div>

<div class="button-container">
  <a href="{% url 'home' %}" class="home-btn">Go back to Home</a>
  <a href="{% url 'agentview' %}" class="home-btn">Renter's Actions</a>
</div>

<style>
  .success-message {
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: #DFF2BF;
    border: 1px solid #4F8A10;
    border-radius: 5px;
    margin: 20px;
    padding: 10px;
  }

  .success-message i {
    color: #4F8A10;
    font-size: 24px;
    margin-right: 10px;
  }

  .success-message p {
    color: #4F8A10;
    font-weight: bold;
    font-size: 16px;
    margin: 0;
  }

  .button-container {
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 20px;
  }

  .home-btn {
    background-color: #4CAF50;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin: 0 10px;
    text-decoration: none;
    font-size: 14px;
  }

  .home-btn:hover {
    background-color: #3e8e41;
  }
</style>

RealStateJA/templates/RealStateJA/searchresults.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Search Results</title>
</head>
<body>
  {% if results %}
    <table>
      <thead>
        <tr>
          <th>City</th>
          <th>State</th>
          <th>Price</th>
          <th>Building Type</th>
          <th>Listing Type</th>
          <th>Number of Bedrooms</th>
          <th>Available Date</th>
          <th>Building Details</th>
        </tr>
      </thead>
      <tbody>
        {% for prop, building in results %}
          <tr>
            <td>{{ prop.location_city }}</td>
            <td>{{ prop.location_state }}</td>
            <td>{{ prop.price }}</td>
            <td>{{ building.get_building_type_display }}</td>
            <td>{{ prop.get_listing_type_display }}</td>
            <td>{{ prop.num_bedrooms }}</td>
            <td>{{ prop.availability }}</td>
            <td>{{ building }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No results found.</p>
  {% endif %}
</body>
</html>

RealStateJA/templates/RealStateJA/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Sign Up</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
    }
    h1 {
      text-align: center;
    }
    form {
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      border: 1px solid #ccc;
      border-radius: 10px;
    }
    fieldset {
      border: none;
      margin-bottom: 20px;
    }
    label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }
    input[type="text"], input[type="number"], input[type="date"] {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
      box-sizing: border-box;
      margin-bottom: 20px;
    }
    input[type="radio"] {
      margin-right: 5px;
    }
    button[type="submit"], button {
      background-color: #4CAF50;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }
    fieldset {
      border: 2px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin-bottom: 20px;
    }

    legend {
      font-size: 1.2em;
      font-weight: bold;
      margin-bottom: 10px;
    }
    button[type="submit"]:hover, button:hover {
      background-color: #3e8e41;
    }
    #agent_fields, #renter_fields {
      margin-top: 20px;
    }
  </style>
</head>

<body>
  <h1>Create a new user</h1>
  <a href="{% url 'home' %}"><button>Go back to Home</button></a>
  <form method="POST">
    {% csrf_token %}
    <form method="post">
      {% csrf_token %}
      <fieldset>
        <legend>Personal Information</legend>
        <label for="name">Name:</label><br>
        <input type="text" id="name" name="name"><br>
        <label for="email_address">Email Address:</label><br>
        <input type="text" id="email_address" name="email_address"><br>
        <label for="telephone">Telephone Number:</label><br>
        <input type="text" id="telephone" name="telephone"><br>
      </fieldset>
      <fieldset>
        <legend>Address Information</legend>
        <label for="street_street_number">Street Number:</label><br>
        <input type="text" id="street_street_number" name="street_street_number"><br>
        <label for="street_street_name">Street Name:</label><br>
        <input type="text" id="street_street_name" name="street_street_name"><br>
        <label for="street_apt_number">Apartment Number:</label><br>
        <input type="text" id="street_apt_number" name="street_apt_number"><br>
        <label for="city">City:</label><br>
        <input type="text" id="city" name="city"><br>
        <label for="state">State:</label><br>
        <input type="text" id="state" name="state"><br>
        <label for="zip">Zip:</label><br>
        <input type="text" id="zip" name="zip"><br>
      </fieldset>
    <p>Are you an agent or a renter?</p>
    <input type="radio" name="user_type" value="agent"> Agent<br>
    <input type="radio" name="user_type" value="renter"> Renter<br><br>
    <div id="agent_fields" style="display:none;">
        <label for="agency">Agency:</label>
        <input type="text" name="agency" id="id_agency"><br><br>
        <label for="license_number">License Number :</label>
        <input type="text" name="license_number" id="license_number"><br><br>
        <label for="commission_rate">Commission Rate (%):</label>
        <input type="text" name="commission_rate" id="commission_rate"><br><br>
    </div>
    <div id="renter_fields" style="display:none;">
      <fieldset>
        <legend>Billing Information</legend>
        <label for="card_number">Card Number:</label>
        <input type="text" id="card_number" name="card_number" onkeyup="formatCreditCard()" maxlength="19"><br><br>
        <script>
        function formatCreditCard() {
          var input = document.getElementById("card_number");
          var value = input.value.replace(/\D/g, "").trim();
          var formattedValue = "";
          for (var i = 0; i < value.length; i++) {
            if (i % 4 === 0 && i !== 0) {
              formattedValue += " ";
            }
            formattedValue += value[i];
          }
          input.value = formattedValue;
        }
        </script>
        <label for="cardholder_name">Cardholder Name:</label>
        <input type="text" name="cardholder_name" id="cardholder_name"><br><br>
        <label for="billing_address">Billing Address:</label>
        <input type="text" name="billing_address" id="billing_address"><br><br>
      </fieldset>
      <fieldset>
        <legend>Additional Information</legend>
        <label for="desired_move_in_date">Desired move in date:</label>
        <input type="date" name="desired_move_in_date" id="id_desired_move_in_date"><br><br>
        <label for="preferred_location_city">Preferred City:</label>
        <input type="text" name="preferred_location_city" id="id_preferred_location_city"><br><br>
        <label for="preferred_location_state">Preferred State:</label>
        <input type="text" name="preferred_location_state" id="id_preferred_location_state"><br><br>
        <label for="budget">Budget:</label>
        <input type="number" name="budget" id="id_budget"><br><br>
      </fieldset>
    </div>
    <button type="submit">Sign up</button>

</form>

<script>
    const agentFields = document.querySelector('#agent_fields');
    const renterFields = document.querySelector('#renter_fields');
    const agentRadio = document.querySelector('input[name="user_type"][value="agent"]');
    const renterRadio = document.querySelector('input[name="user_type"][value="renter"]');

    agentRadio.addEventListener('change', () => {
        agentFields.style.display = 'block';
        renterFields.style.display = 'none';
    });

    renterRadio.addEventListener('change', () => {
        renterFields.style.display = 'block';
        agentFields.style.display = 'none';
    });

    const emailField = document.getElementById('email_address');
    const signupButton = document.getElementById('signup_button');

    emailField.addEventListener('input', () => {
      if (emailField.validity.valid) {
        signupButton.removeAttribute('disabled');
      } else {
        signupButton.setAttribute('disabled', true);
      }
    });
</script>

RealStateJA/templates/RealStateJA/success.html

<div class="success-message">
  <i class="fa fa-check-circle"></i>
  <p>Sign up successful! Thank you for registering!</p>
</div>

<div class="button-container">
  <a href="{% url 'home' %}" class="home-btn">Go back to Home</a>
  </div>

<style>
  .success-message {
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: #DFF2BF;
    border: 1px solid #4F8A10;
    border-radius: 5px;
    margin: 20px;
    padding: 10px;
  }

  .success-message i {
    color: #4F8A10;
    font-size: 24px;
    margin-right: 10px;
  }

  .success-message p {
    color: #4F8A10;
    font-weight: bold;
    font-size: 16px;
    margin: 0;
  }

  .button-container {
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 20px;
  }

  .home-btn {
    background-color: #4CAF50;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    margin: 0 10px;
    text-decoration: none;
    font-size: 14px;
  }

  .home-btn:hover {
    background-color: #3e8e41;
  }
</style>